# Lookup data the generator builds on: the country-to-region mapping (for the map
# and the filters) and the product catalogue with cost and sell prices (for profit).

# Country, ISO-3 code (the map needs it to shade each country), sub-region,
# continent, and a weight that skews how much business each market gets.
# It's a German company, so DACH leads, then the rest of Europe.
COUNTRIES = [
    # country, iso3, sub_region, continent, weight
    ("Germany",        "DEU", "DACH",            "Europe",   30),
    ("Austria",        "AUT", "DACH",            "Europe",   10),
    ("Switzerland",    "CHE", "DACH",            "Europe",   10),
    ("Netherlands",    "NLD", "Benelux",         "Europe",    7),
    ("Belgium",        "BEL", "Benelux",         "Europe",    5),
    ("Luxembourg",     "LUX", "Benelux",         "Europe",    2),
    ("France",         "FRA", "Western Europe",  "Europe",    8),
    ("Italy",          "ITA", "Western Europe",  "Europe",    6),
    ("Poland",         "POL", "Central Europe",  "Europe",    5),
    ("Czechia",        "CZE", "Central Europe",  "Europe",    4),
    ("United Kingdom", "GBR", "British Isles",   "Europe",    7),
    ("Ireland",        "IRL", "British Isles",   "Europe",    3),
    ("Spain",          "ESP", "Iberia",          "Europe",    5),
    ("Portugal",       "PRT", "Iberia",          "Europe",    3),
    ("Sweden",         "SWE", "Nordics",         "Europe",    4),
    ("Denmark",        "DNK", "Nordics",         "Europe",    3),
    ("Norway",         "NOR", "Nordics",         "Europe",    3),
    ("Finland",        "FIN", "Nordics",         "Europe",    2),
    ("Croatia",        "HRV", "Balkans",         "Europe",    2),
    ("Serbia",         "SRB", "Balkans",         "Europe",    2),
    ("Slovenia",       "SVN", "Balkans",         "Europe",    2),
    ("Bulgaria",       "BGR", "Balkans",         "Europe",    2),
    ("Romania",        "ROU", "Balkans",         "Europe",    3),
    ("Greece",         "GRC", "Balkans",         "Europe",    2),
    ("United States",  "USA", "North America",   "Americas",  9),
    ("Canada",         "CAN", "North America",   "Americas",  4),
    ("Mexico",         "MEX", "North America",   "Americas",  3),
    ("Brazil",         "BRA", "South America",   "Americas",  3),
    ("Argentina",      "ARG", "South America",   "Americas",  2),
    ("Chile",          "CHL", "South America",   "Americas",  2),
    ("China",          "CHN", "East Asia",       "Asia",      6),
    ("Japan",          "JPN", "East Asia",       "Asia",      5),
    ("South Korea",    "KOR", "East Asia",       "Asia",      3),
    ("India",          "IND", "South Asia",      "Asia",      4),
    ("Singapore",      "SGP", "Southeast Asia",  "Asia",      3),
    ("Thailand",       "THA", "Southeast Asia",  "Asia",      2),
    ("Malaysia",       "MYS", "Southeast Asia",  "Asia",      2),
    ("Indonesia",      "IDN", "Southeast Asia",  "Asia",      2),
    ("UAE",            "ARE", "Middle East",     "Asia",      3),
    ("Saudi Arabia",   "SAU", "Middle East",     "Asia",      2),
    ("Australia",      "AUS", "Oceania",         "Oceania",   3),
    ("New Zealand",    "NZL", "Oceania",         "Oceania",   2),
]

# The catalogue. Cost price is what we pay, sell price is what the customer pays
# before discount. Margins vary on purpose - a few are thin so the P&L has contrast.
# article_no, name, category, cost_price, sell_price
PRODUCTS = [
    ("A-1001", "Cordless Drill 18V",       "Power Tools",  78.00, 149.00),
    ("A-1002", "Impact Driver 18V",        "Power Tools",  82.00, 159.00),
    ("A-1003", "Angle Grinder 125mm",      "Power Tools",  44.00,  89.00),
    ("A-1004", "Circular Saw 190mm",       "Power Tools",  96.00, 175.00),
    ("A-1005", "Rotary Hammer SDS",        "Power Tools", 145.00, 269.00),
    ("A-1006", "Heat Gun 2000W",           "Power Tools",  29.00,  59.00),
    ("A-2001", "Screwdriver Set 32pc",     "Hand Tools",   12.00,  34.00),
    ("A-2002", "Adjustable Wrench 250mm",  "Hand Tools",    6.50,  18.00),
    ("A-2003", "Claw Hammer 16oz",         "Hand Tools",    5.00,  14.00),
    ("A-2004", "Tape Measure 8m",          "Hand Tools",    3.20,   9.50),
    ("A-2005", "Spirit Level 600mm",       "Hand Tools",    8.00,  22.00),
    ("A-2006", "Plier Set 3pc",            "Hand Tools",    9.50,  26.00),
    ("A-3001", "Safety Helmet",            "Safety",       11.00,  27.00),
    ("A-3002", "Safety Glasses (10pk)",    "Safety",        7.00,  19.00),
    ("A-3003", "Work Gloves (5pk)",        "Safety",        9.00,  21.00),
    ("A-3004", "Ear Defenders",            "Safety",        6.00,  15.00),
    ("A-3005", "Hi-Vis Vest",              "Safety",        4.50,  11.00),
    ("A-4001", "Drill Bit Set 50pc",       "Accessories",  10.00,  29.00),
    ("A-4002", "Saw Blade 190mm",          "Accessories",   7.50,  19.00),
    ("A-4003", "Sanding Discs (25pk)",     "Accessories",   5.00,  13.00),
    ("A-4004", "Grinding Wheel (10pk)",    "Accessories",   8.00,  17.00),
    ("A-5001", "Tool Storage Case",        "Storage",      22.00,  49.00),
    ("A-5002", "Tool Belt",                "Storage",      14.00,  35.00),
    ("A-5003", "Workshop Trolley",         "Storage",      88.00, 169.00),
    ("A-6001", "Battery Pack 5Ah",         "Batteries",    38.00,  79.00),
    ("A-6002", "Fast Charger",             "Batteries",    24.00,  44.00),
    ("A-6003", "Battery Twin Pack 4Ah",    "Batteries",    62.00, 119.00),
]
